NUMBER 1

In [8]:
import numpy as np

x = np.random.random ((5,5))
x

array([[0.56259915, 0.84999621, 0.71520988, 0.67816061, 0.78677393],
       [0.16209153, 0.25232463, 0.52895514, 0.50041891, 0.09568559],
       [0.362208  , 0.43990061, 0.83252127, 0.28077459, 0.47381109],
       [0.37296269, 0.15483899, 0.0318773 , 0.59180115, 0.75846337],
       [0.6095181 , 0.82002915, 0.26896116, 0.94309722, 0.14858347]])

In [9]:
#TO GET THE MEAN

m = x.mean ()
m

np.float64(0.4888625490492419)

In [10]:
#TO GET STANDARD DEVIATION
s = x.std ()
s

np.float64(0.26249754566879363)

In [11]:
#Nromalization
z = x-m/s
z

np.save('X_normalized.npy',z)

NUMBER 2

In [13]:
a = np.arange (1, 101)
a.resize (10,10)
ndarray = a**2
ndarray

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [22]:
d = ndarray [ ndarray % 3 == 0 ]
d

np.save('

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])